/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;

import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.net.UnknownHostException;
import java.util.logging.Level;
import java.util.logging.Logger;
import static java.lang.Thread.sleep;

import javax.swing.JFrame;
import javax.swing.WindowConstants;

import data.*;
import database.*;
import network.*;


/**
 *
 * @author HaHa
 */
@SuppressWarnings({ "serial", "unused" })
public class LoginForm extends javax.swing.JFrame {

	private Interface inter;
	static Thread listenTCP = null;
	static Thread listenUDP = null;
	static TCPServer runnableTCP = null;
	static UDPServer runnableUDP = null;
	private static final History history = null;


	/**
	 * Creates new form LoginForm
	 */
	public LoginForm() {
		initComponents();
		this.setLocationRelativeTo(null); //center in the screen
	}

	public LoginForm(Interface inter) {
		this.inter = inter;
		initComponents();
		this.setLocationRelativeTo(null); //center in the screen
		jTextFieldHost.setText(inter.getUser().getHost());
	}


	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelLogin = new javax.swing.JLabel();
        jLabelClose = new javax.swing.JLabel();
        jLabelMin = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabelPseudo = new javax.swing.JLabel();
        jLabelHost = new javax.swing.JLabel();
        jTextFieldHost = new javax.swing.JTextField();
        jButtonLogin = new javax.swing.JButton();
        jLabelWarning = new javax.swing.JLabel();
        jTextFieldPseudo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51,153,255));
        jPanel1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel1MouseDragged(evt);
            }
        });

        jLabelLogin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelLogin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelLogin.setText("Login");

        jLabelClose.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelClose.setForeground(new java.awt.Color(255, 255, 255));
        jLabelClose.setText("X");
        jLabelClose.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelCloseMouseClicked(evt);
            }
        });

        jLabelMin.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabelMin.setForeground(new java.awt.Color(255, 255, 255));
        jLabelMin.setText("-");
        jLabelMin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jLabelMin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabelMinMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelLogin)
                .addGap(106, 106, 106)
                .addComponent(jLabelMin, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelClose)
                .addGap(12, 12, 12))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelMin, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                .addComponent(jLabelLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jLabelClose, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(52, 73, 94));
        jPanel2.setPreferredSize(new java.awt.Dimension(407, 267));

        jLabelPseudo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelPseudo.setForeground(new java.awt.Color(236, 240, 241));
        jLabelPseudo.setText("Username :");

        jLabelHost.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelHost.setForeground(new java.awt.Color(236, 240, 241));
        jLabelHost.setText("Host :");

        jTextFieldHost.setEditable(false);
        jTextFieldHost.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldHost.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldHost.setForeground(new java.awt.Color(228, 241, 254));
        jTextFieldHost.setHorizontalAlignment(javax.swing.JTextField.LEFT);

        jButtonLogin.setBackground(new java.awt.Color(52, 152, 219));
        jButtonLogin.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButtonLogin.setForeground(new java.awt.Color(0, 0, 0));
        jButtonLogin.setText("Login");
        jButtonLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });

        jLabelWarning.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelWarning.setForeground(new java.awt.Color(241, 130, 141));
        jLabelWarning.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelWarning.setText("Please choose your username"); // NOI18N

        jTextFieldPseudo.setBackground(new java.awt.Color(108, 122, 137));
        jTextFieldPseudo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTextFieldPseudo.setForeground(new java.awt.Color(228, 241, 254));
        jTextFieldPseudo.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextFieldPseudo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPseudoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelWarning, javax.swing.GroupLayout.DEFAULT_SIZE, 407, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelPseudo)
                    .addComponent(jLabelHost))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldHost, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 249, Short.MAX_VALUE)
                    .addComponent(jTextFieldPseudo))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(149, 149, 149))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabelWarning)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPseudo)
                    .addComponent(jTextFieldPseudo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHost)
                    .addComponent(jTextFieldHost, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(jButtonLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	protected void jLabelCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelCloseMouseClicked
		try {
			new UDPClientThread().sendDisconnect(inter);
		} catch (UnknownHostException ex) {
			Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
		}
		System.exit(0);
	}//GEN-LAST:event_jLabelCloseMouseClicked

	protected void jLabelMinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabelMinMouseClicked
		this.setState(JFrame.ICONIFIED);
	}//GEN-LAST:event_jLabelMinMouseClicked

	protected void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt){//GEN-FIRST:event_jButtonLoginActionPerformed
		if (this.jTextFieldPseudo.getText().equals("")) {
			this.jLabelWarning.setText("User nickname cannot be empty.");
		} else {
			try {
				this.jLabelWarning.setText("Connecting... Please Wait");
				/* Create a node with the nickname and the host address */
				User user = new User(jTextFieldHost.getText(),jTextFieldPseudo.getText());
				this.inter = new Interface(user);

				/* Start a server thread TCP to listen */
				if (listenTCP != null && runnableTCP != null) {
					runnableTCP.terminate();
					listenTCP.join();
				}
				runnableTCP = new TCPServer(this.inter, History.getInstance());
				listenTCP = new Thread(runnableTCP);
				listenTCP.start();

				/* This thread is used to receive  broadcast by UDP*/
				if (listenUDP != null && runnableUDP != null) {
					runnableUDP.terminate();
					listenUDP.join();
				}
				runnableUDP = new UDPServer(this.inter);
				listenUDP = new Thread(runnableUDP);
				listenUDP.start();

				/* Send a broadcast when log in*/
				new UDPClientThread().sendBroadcast(this.inter);

				/* Open homepage if the nickname is unique*/
				sleep(10);
				if (this.inter.checkPseudo()) {
					new UDPClientThread().sendBroadcast(this.inter);
					this.inter.getHome().display();
					this.setVisible(false);
					setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
					this.dispose();
				} else {
					new UDPClientThread().sendDisconnect(this.inter);
					this.jLabelWarning.setText("WARNING : This name has been used !");
				}

				System.out.println(this.inter);
				System.out.println(this.inter.checkPseudo());

			} catch (IOException | InterruptedException ex) {
				Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
	}//GEN-LAST:event_jButtonLoginActionPerformed

	private void jTextFieldPseudoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPseudoKeyPressed
		if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
			if (this.jTextFieldPseudo.getText().equals("")) {
				this.jLabelWarning.setText("User nickname cannot be empty.");
			} else {
				try {
					this.jLabelWarning.setText("Connecting... Please Wait");
					/* Create a node with the nickname and the host address */
					User user = new User(jTextFieldHost.getText(),jTextFieldPseudo.getText());
					this.inter = new Interface(user);


					/* Start a server thread TCP to listen */
					if (listenTCP != null && runnableTCP != null) {
						runnableTCP.terminate();
						listenTCP.join();
					}
					runnableTCP = new TCPServer(this.inter,History.getInstance());
					listenTCP = new Thread(runnableTCP);
					listenTCP.start();

					/* This thread is used to receive le broadcast by UDP*/
					if (listenUDP != null && runnableUDP != null) {
						runnableUDP.terminate();
						listenUDP.join();
					}
					runnableUDP = new UDPServer(this.inter);
					listenUDP = new Thread(runnableUDP);
					listenUDP.start();

					/* Send a broadcast when log in*/
					new UDPClientThread().sendBroadcast(this.inter);

					/* Open home if the nickname is unique*/
					sleep(10);
					if (this.inter.checkPseudo()) {
						new UDPClientThread().sendBroadcast(this.inter);
						this.inter.getHome().display();
						this.setVisible(false);
						setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
						this.dispose();
					} else {
						new UDPClientThread().sendDisconnect(this.inter);
						this.jLabelWarning.setText("WARNING : This name has been used !");
					}
					
					System.out.println(this.inter);
					System.out.println(this.inter.checkPseudo());

				} catch (IOException | InterruptedException ex) {
					Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
				}

			}
		}
	}//GEN-LAST:event_jTextFieldPseudoKeyPressed

    private void jPanel1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel1MouseDragged
        int coordinateX = evt.getXOnScreen();
        int coordinateY = evt.getYOnScreen();
        this.setLocation(coordinateX, coordinateY);
    }//GEN-LAST:event_jPanel1MouseDragged

	public void display(){
		this.setLocationRelativeTo(null); 
		this.setVisible(true);
	}

	public void setTitle(String title){
		jLabelWarning.setText(title);
	}


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JLabel jLabelClose;
    private javax.swing.JLabel jLabelHost;
    private javax.swing.JLabel jLabelLogin;
    private javax.swing.JLabel jLabelMin;
    private javax.swing.JLabel jLabelPseudo;
    private javax.swing.JLabel jLabelWarning;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextFieldHost;
    private javax.swing.JTextField jTextFieldPseudo;
    // End of variables declaration//GEN-END:variables
}